@echo off
cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc  -G "MinGW Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -B build/release
cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -G "MinGW Makefiles" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -B build/debug
